### ISSUE TITLE
Polarity of D1 LED in schematic

### ISSUE THREAD

**Issue by jmeckstroth** [teapotlaboratories/feather-rak3172#1]
Is not the polarity of D1 shown incorrect on the schematic?

**Comment by jmeckstroth** [comment]
Please update the Shared Project files in PCBWAY to correct the D1 LED polarity.  Thanks!

**Comment by aldwinhermanudin** [comment]
Hi @jmeckstroth ,

Thanks for raising the issue.
I'll update it next week, as I'm currently away from my computer. 
As for now, you can use the current gerber file in `main` branch, as it already has the fix.
Thanks!

**Comment by jmeckstroth** [comment]
FYI,  the Teapot Feather boards with a US915 version of the RAK3172 that I procured from PCBWAY function fine.  I am considering a variant of the Teapot board that brings TX2/RX2 to the Feather pins instead of TX1/RX1, in order to use the module with another MCU using the AT Command means of controlling the RAK3172.

**Comment by aldwinhermanudin** [comment]
Thanks, glad to hear it works.
Now that I think of it, that's a good idea.
