### ISSUE TITLE
No issue, just ask about picture

### ISSUE THREAD

**Issue by NamNamIoT** [teapotlaboratories/feather-rak3172#2]
Hello, I am very impressed with your product.
I would like to know which created the photo that depicts the pinout. 
What software was it created with?

![image](https://github.com/teapotlaboratories/feather-rak3172/assets/49629370/d926cb1f-2525-4b9e-bf6b-32095b54bda8)

Thank you very much bro!

**Comment by aldwinhermanudin** [comment]
Hi @NamNamIoT,

Thanks! Honestly it's a little bit manual.

- Top Board: From KiCAD ( there's a Orthographic Projection option in the 3D PCB Viewer )
- Pin Legend and Name: https://github.com/ATMakersOrg/HoldingArea/blob/master/FeatherTemplate.svg
- I use Inkscape to combine those together.

You can see tutorial [here](https://blog.adafruit.com/2019/07/11/automating-the-making-of-beautiful-pinout-diagrams-for-microcontroller-boards-documentation-at_makers/)

**Comment by NamNamIoT** [comment]
Thank you verymuch pro!
